// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QVn5KF-qao4jefjiGlEuIeD8R53DgKU',
    appId: '1:791309423472:web:239b1c2ffe24c5d7edf5b5',
    messagingSenderId: '791309423472',
    projectId: 'grandrenaiinventory',
    authDomain: 'grandrenaiinventory.firebaseapp.com',
    storageBucket: 'grandrenaiinventory.firebasestorage.app',
    measurementId: 'G-KLR6E27W48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0i84PdfxP6X0wiIdcYEyBcIDaaLuHgCg',
    appId: '1:791309423472:android:9ba6ec8fc3ed9daeedf5b5',
    messagingSenderId: '791309423472',
    projectId: 'grandrenaiinventory',
    storageBucket: 'grandrenaiinventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpcxIKtMltjD-Byx3jA78clRqpNZQqSk',
    appId: '1:791309423472:ios:61ad8c6c34de9a19edf5b5',
    messagingSenderId: '791309423472',
    projectId: 'grandrenaiinventory',
    storageBucket: 'grandrenaiinventory.firebasestorage.app',
    iosBundleId: 'com.example.grandRenaiInventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVpcxIKtMltjD-Byx3jA78clRqpNZQqSk',
    appId: '1:791309423472:ios:61ad8c6c34de9a19edf5b5',
    messagingSenderId: '791309423472',
    projectId: 'grandrenaiinventory',
    storageBucket: 'grandrenaiinventory.firebasestorage.app',
    iosBundleId: 'com.example.grandRenaiInventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-QVn5KF-qao4jefjiGlEuIeD8R53DgKU',
    appId: '1:791309423472:web:2b6ff831c9e57d36edf5b5',
    messagingSenderId: '791309423472',
    projectId: 'grandrenaiinventory',
    authDomain: 'grandrenaiinventory.firebaseapp.com',
    storageBucket: 'grandrenaiinventory.firebasestorage.app',
    measurementId: 'G-W190G51FG5',
  );
}
